export const CONNECT_SOCKET = 'CONNECT_SOCKET'

export const LOGIN_TWITTER = 'LOGIN_TWITTER'
export const LOGOUT_TWITTER = 'LOGOUT_TWITTER'

export const OPEN_POPUP = 'OPEN_POPUP'
export const CLOSE_POPUP = 'CLOSE_POPUP'

export const GET_USER_TIMELINES = 'GET_USER_TIMELINES'
export const GET_HOME_TIMELINES = 'GET_HOME_TIMELINES'
export const GET_LIKE_TIMELINES = 'GET_LIKE_TIMELINES'

export const GET_FOLLOWERS = 'GET_FOLLOWERS'
export const GET_FRIENDS = 'GET_FRIENDS'
